controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

app_cars:
    path: /cars
    controller: App\Controller\UsedCarsController::index
    methods: [GET]

app_cars_filter:
    path: /cars/filter
    controller: App\Controller\UsedCarsController::filterCars
    methods: [POST]

admin_index:
    path: /admin
    controller: App\Controller\AdminController::index
    methods: [GET]

